codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 1
  round: nearest
  range: "80...100"

  status:
    project:
      default:
        target: 90
        threshold: 5
    patch:
      default:
        target: 90
        threshold:
    changes: no

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
